# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
addons:
   apt:
      packages:
         - xvfb
         - xauth
         - libgtk-3-0
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia 'Pkg.clone("https://github.com/paulmthompson/SpikeSorting.jl")'
  - xvfb-run julia --check-bounds=yes --depwarn=no -e 'Pkg.clone(pwd()); Pkg.build("Intan"); Pkg.test("Intan"; coverage=true)'
  - julia 'Pkg.rm("SpikeSorting")'
after_success:
  - julia -e 'cd(Pkg.dir("Intan")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
